### ISSUE TITLE
remove auto save to h5

### ISSUE THREAD

**Issue by rgcoe** [WEC-Sim/WDRT#1]
It looks like the `h5` files that get automatically saved by `fetchFromWeb` are quite large (~10 MB). Thus, I don't really think there's much of an advantage to having these over the raw `txt` files. Let's remove this functionality for now.

NOTE - This is on the `refactor` branch

**Comment by tyleresterly** [comment]
Files are saved as a .txt by default rather than .h5, but the functionality to save as an h5 still exists.
