### ISSUE TITLE
Slope of PCA contour

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#10]
Hi @aubreyeckert ,

I'm having trouble reconciling the shape of a PCA contour with the distribution of the underlying data.
![wis_ _st63044 _50-year_contours_tm](https://user-images.githubusercontent.com/12396856/36034693-dba2f968-0d82-11e8-8552-36a62cad4243.png)

In my experience with WDRT so far, the contours from the PCA approach have seemed the most reliable. 
But with this data set, I can't figure out why the peak of the contour is shifted so far to the higher periods. 

This study is using hindcast data from the US Army Corp of Engineers Wave Information Studies:
http://wis.usace.army.mil/wis_products.html?dmn=atlantic&staid=63044&lat=42.92&lon=-70.58&dep=-45
[Despite what the x-axis label says,] I'm using the mean period (Integral of 1.0/f*E(f,θ)). 

Would you be willing to take a look and see if this result makes sense to you?
[envSampling.zip](https://github.com/WEC-Sim/WDRT/files/1711469/envSampling.zip)

Thanks!

**Comment by aubreyeckert** [comment]
Hello @Toby-D,

We are currently putting together a paper that tries to understand why certain contour methods (including PCA) perform poorly with some datasets and will let you know when it is available. 

In the meantime, I would suggest that you look at the empirical density of your data. I suspect that there may be many points concentrated in the mid-Te, low-Hs region that could be skewing the contour. 

Best,
Aubrey

**Comment by Toby-D** [comment]
OK, I'll try that.

Thanks Aubrey.
