### ISSUE TITLE
Using ESSC with missing data

### ISSUE THREAD

**Issue by mbruggs** [WEC-Sim/WDRT#12]
Thanks for making WRDT publicly available!

I would like to do some contour analysis on  buoy data which has Hs and Tp value at 30 minute intervals. Unfortunately the record is not entirely continuous with gaps in the timeseries.

I've had a look through the WDRT documentation and code and couldn't find anywhere that mentions how missing data is dealt with explicitly. Do you know if there is a method of dealing with records with missing entries?

Thanks in adavance!

**Comment by rgcoe** [comment]
Thanks for your interest in the WDRT. I think there are probably two approaches for this scenario:

1. Fill in the gaps via some sort of interpolation
2. Ignore the gaps (remove them)

Hope this helps!

On May 17, 2018, at 8:38 AM, Mark Bruggemann <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for making WRDT publicly available!

I would like to do some contour analysis on buoy data which has Hs and Tp value at 30 minute intervals. Unfortunately the record is not entirely continuous with gaps in the timeseries.

I've had a look through the WDRT documentation and code and couldn't find anywhere that mentions how missing data is dealt with explicitly. Do you know if there is a method of dealing with records with missing entries?

Thanks in adavance!

**Comment by mbruggs** [comment]
Hi Ryan,

Thanks for getting back to me - in the end I ignored the gaps as you suggested.

Mark
