### ISSUE TITLE
Wave directionality

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#15]
Hi WDRT Team,

Has there been any progress towards incorporating wave directionality into the ESSC module? (As I understand it, this would ideally just be another dimension in the PCA, correct?)

Assuming the code hasn't been extended to account for directionality, I'd be interested to know your thoughts on potential workarounds. A couple that come to mind are:

1. Bin the historical data by wave direction and run PCA on each bin. (But this introduces issues of non-uniform spacing in time). 
2. Apply PCA to the monthly or yearly maximum wave heights from each direction. (But this yields a relatively small set of points from most available data sets.)
3. Discard wave period and simply run PCA on wave height vs. direction. (Besides the obvious loss of period and steepness info, the pitfalls here aren't clear to me.)
4. Others?

I'd appreciate your thoughts!

Thanks,
Toby.

**Comment by aubreyeckert** [comment]
Hi Toby,

We have not been able to incorporate more than the two current dimensions we have available in the ESSC module for calculating environmental contours, whether through PCA or any of the other contour methods.

The difficulty in extending the contour methods to a third dimension would be in defining the joint distribution in terms of all of the variables. While you could use the workarounds that you mentioned, the ESSC module is designed with the Hs/T joint distribution inherent to the calculations. This includes selected marginal distributions that were found to do a good job of modeling the dependence of the components that come out of the PCA transformation. Problematically, if you include different variables in the PCA, even if ultimately you still have two components, these marginal distributions and their dependence structure would likely not capture the relationship between these components as well as could be done. At this point the ESSC is only designed with Hs/T in mind. 

If you were planning on implementing your workarounds outside of the ESSC, I do think that some of the dependence workaround that you mentioned could be interesting to try. 

Please let me know if I can provide any clarification.

Best,
Aubrey

**Comment by rgcoe** [comment]
Toby - Do you have any interest in developing this as a contribution to WDRT?

Ryan

**Comment by Toby-D** [comment]
@aubreyeckert, your points make perfect sense. Thanks. 
I applied the PCA method to the monthly maximum wave heights from each directional bin. Qualitatively, the results seem reasonable, though I'm not convinced that my approach is mathematically rigorous.  In case anyone is interested, the computed 50-year contour for waves from compass headings between 0 and 36 degrees at CDIP160 are shown below. 

@ryancoe I would be interested in improving this, of course. But realistically, my availability to do something like that is rather limited at this point. Also, I would have a long way to go before my understanding of the subtleties of the different methods is comparable to that of Aubrey's or any of the others who have worked on this in depth.

![cdip_ _160 _50-year_contours_wavedp 0-36deg](https://user-images.githubusercontent.com/12396856/46754993-f5be1700-cc91-11e8-9044-d689762ba55a.png)

**Comment by rgcoe** [comment]
This looks neat @Toby-D, thanks for sharing!
