### ISSUE TITLE
MLER

### ISSUE THREAD

**Issue by wyg110sjtu** [WEC-Sim/WDRT#16]
Dear  WDRT developers: 
Your WDRT examples has an example_MLER_testrun.py whose first three lines of codes are as follows:
"RAOdir      = './data/RAO_data/'
outputDir   = './data/TestData/'
import mler"
Is the third line of code "import mler" correct or not?

Today I run your example_MLER_testrun.py and obtained the follwing warnings on my computer screen:
"Python 2.7.10 |Anaconda 2.3.0 (32-bit)| (default, May 28 2015, 17:02:00) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\wyg\Anaconda\lib\idlelib\run.py", line 324, in runcode
    exec code in self.locals
  File "D:\WDRT2\WDRT-master\examples\example_MLER_testrun.py", line 3, in <module>
    import mler
ImportError: No module named mler
>>> ".

Why? Please kind reply me. 
Many thanks!

John Wang

**Comment by rgcoe** [comment]
@wyg110sjtu - Thank you for your interest in this tool. We will work to find a solution to this problem.

**Comment by ssolson** [comment]
@wyg110sjtu Could you confirm if you ever found a solution to your issue? The code has been updated to Python 3 since this issue was opened so I am suggesting this issue be closed @ryancoe .
