### ISSUE TITLE
Merge Branch WDRT_Py3

### ISSUE THREAD

**Issue by ssolson** [WEC-Sim/WDRT#22]
@aubreyeckert  can we merge the commit you made on March 16 (commit 7926a1aa77824be925b2890b4f98e1d0cfb45c77) to the WDRT_Py3 branch into the master branch?

**Comment by aubreyeckert** [comment]
@ssolson That should be fine as long as it should still run the same way (I expect it will). Are you just porting everything over to Python 3 on the master?
