### ISSUE TITLE
Merge Branch Branch origin/WDRT_Py3

### ISSUE THREAD

**Issue by ssolson** [WEC-Sim/WDRT#24]
@zmorrell-sand It looks like this branch can be merged. It has a couple of print statements and changes to the way data is loaded.

Can you review the 2 commits and let me know if they should be merged?

**Comment by zmorrell-sand** [comment]
@ssolson ,
It would be better to Merge WDRT_Py3 rather than origin/WDRT_Py3.  I merged those two branches a while back, and if I recall Aubrey's most recent push fixes a bug that was in origin/WDRT_Py3.  The print statements were put in to help find what was causing the bug.

**Comment by ssolson** [comment]
Perfect I am merging WDRT_Py3 now. 

Can I delete origin/WDRT_Py3?

**Comment by ssolson** [comment]
Relevant code from this branch is included in PR #36
