### ISSUE TITLE
NDBC46022.h5: no "dateList" 

### ISSUE THREAD

**Issue by ssolson** [WEC-Sim/WDRT#29]
When trying to run `example_envSampling.py` I point to the location of NDBC46022.h5 (In  the default location examples/data. ). 

 When running this I get an error suggesting that 'dateList' does not exist:
![image](https://user-images.githubusercontent.com/13438942/81594745-a0bb1900-937e-11ea-8475-8ac9ab746440.png)

To check that I have not modified the file I separately downloaded NDBC46022.h5 from the repository.

I then loaded it using h5py to confirm that this key does not exist as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/13438942/81594927-e1b32d80-937e-11ea-8bf7-5c48ed060a91.png)

The line of code calling for `dateList` is on ESSC.py here:

https://github.com/WEC-Sim/WDRT/blob/0ae5969dbe5f6fb192854414f742055c61d9a138/WDRT/ESSC.py#L3005

**Comment by ssolson** [comment]
@zmorrell-sand any ideas on how to fix this?

**Comment by ssolson** [comment]
From the `NDBC46022.h5` files history I downloaded the version from the previous commit f26736e1af5cac2e20e2a21141735e4501c2ceaf. This version differs is a couple of ways e.g. It is about twice as big at 6.11MB, the top level of keys only contains "buoy_Data", and contains the `dateList` key missing from the previous commit. 

![image](https://user-images.githubusercontent.com/13438942/81741272-89059280-945b-11ea-9d38-f37ac0ca6cd5.png)

Using this version of the data seems to fix the issue.
@zmorrell-sand could you comment on if this version of the data should be reinstated?

https://github.com/WEC-Sim/WDRT/blob/f26736e1af5cac2e20e2a21141735e4501c2ceaf/examples/data/NDBC46022.h5

**Comment by ssolson** [comment]
@zmorrell-sand could you push your working local version to a featureBranch on your fork so that I can check it out as well?

**Comment by zmorrell-sand** [comment]
@ssolson 
I have pushed the working version of ESSC.py to the "features" branch on my Fork.  The only change that I noticed from the file differences that I think could be causing this issue is line 2690 of the changes [here](https://github.com/zmorrell-sand/WDRT/commit/2938d81d1a02e0ca08e471d62d7f6dc290941f6d).   If the issue doesn't lie in the ESSC file, I would guess that it has something to do with the MLER toolbox.  I am rerunning the example file right now with just this change to see how the results are impacted.

**Comment by zmorrell-sand** [comment]
@ssolson 
The problem does seem to be in ESSC.py, as i was able to get the example to run in its entirety.  I will start changing the ESSC.py (removing pointless print statements, etc) to see if I can figure out exactly what is causing the issue.  Ideally I will know where the break is by the end of the day.

Edit: This  was a fix for the fetchFromWeb issue, not the h5 file.  More work to come to fix h5 file

**Comment by zmorrell-sand** [comment]
@ssolson 
I believe I have found a fix.  It looks like the issue arises from the repository using an old file for the buoy, so I just regenerated it and tried loading the regenerated file.  That was successful.  I will overwrite the old NDBC46022.h5 file with a working one on my machine, make sure that it still works, and upload the fixed version, along with fixes for issues 34 and 35.

**Comment by zmorrell-sand** [comment]
@ssolson I have submitted a PR with the fixes for this, issue 29, 34, 35.

**Comment by zmorrell-sand** [comment]
@ssolson I think I have found the root of what caused this issue in the first place.  In the past, the example_env file tried to save both the contours and the buoy in the same file, which was causing the h5 file to get overwritten.  It looks like this was remedied by just changing the filepath associated with each file.  The contour h5 file is used in example_contourApproach.py, The best solution moving forward would probably be to respecify the file output location in example_envSampling for the files to remove the ambiguity.
