### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by rgcoe** [WEC-Sim/WDRT#3]
@sedwardsand helped point out a number of areas for improvement in our installation documentation (http://wec-sim.github.io/WDRT/installation.html).

- [x] Provide link/instructions on downloading `git`
- [x] Provide link/instructions on configuring PYTHONPATH

@sedwardsand - Is there anything I've missed here?

**Comment by sedwardsand** [comment]
Yes, that's all I have written down.

**Comment by ghost** [comment]
A link has been provided for downloading git. I will add a section on configuring PYTHONPATH in the Troubleshooting section.

**Comment by aubreyeckert** [comment]
Per Bibiana would be helpful for Tyler to provide info on configuring PYTHONPATH.

**Comment by rgcoe** [comment]
@tyleresterly - Please add some additional instructions on configuring a PYTHONPATH

**Comment by tyleresterly** [comment]
Instructions for configuring a PYTHONPATH in both Windows and Linux/OSX have been added
