### ISSUE TITLE
MLER_toolbox vs mler

### ISSUE THREAD

**Issue by ssolson** [WEC-Sim/WDRT#38]
Currently, the repository has duplicate code in the `MLER_toolbox` and `mler` folder. It looks to me like commit 4d51d5194fe2a4942e3c02f2b58d833abfb9d732 by @zmorrell-sand repackaged  `MLER_toolbox` as `mler` and that the prior can be removed from the repository.

@zmorrell-sand is there any reason to keep both from a code functionality point of view?

**Comment by ewquon** [comment]
Repackaging is a good idea and the example code has been updated so I don't see any need to keep `MLER_toolbox`.

**Comment by yuyihsiang** [comment]
Agree

**Comment by ssolson** [comment]
supersedes #21
