### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by rgcoe** [WEC-Sim/WDRT#4]
Add a `setup.py` file. Can look at example here: https://github.com/WEC-Sim/bemio/blob/master/setup.py

This may help to partially resolve some issues with people setting their `PYTHONPATH` as mentioned in #3.

**Comment by tyleresterly** [comment]
Committed a preliminary version of the setup.py file with a few fields filled in, as well as the dependencies list. We can continue to add fields and descriptions in the future, but for now it installs the package and eliminates the need for a user to setup their PYTHONPATH
