### ISSUE TITLE
Bug: Using bootstrap with BivariateKDE contour

### ISSUE THREAD

**Issue by wyg110sjtu** [WEC-Sim/WDRT#47]
Dear WDRT developers:

      I am very much hornored to contact you.  I want to obtain the bootstrap confidence interval for a BivariateKDE contour using WDRT.  I first added two lines of codes to "ESSC.py
def bootStrap(self, boot_size=1000, plotResults=True)" as follows:

elif self.method == "BivariateKDE":
                essccopy = BivariateKDE(buoycopy, self.Ndata, self.max_T, self.max_Hs)

Then I run the WDRT routine for the  BivariateKDE contour of NDBC 44020 including the  following two lines of codes:
nb_steps = 1000
BivariateKDE44020.bootStrap(boot_size=10)

However, I got the following warnings on my computer screen:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    BivariateKDE44020.bootStrap(boot_size=10)
  File "build\bdist.win-amd64\egg\WDRT\ESSC.py", line 356, in bootStrap
    Hs_Return_Boot = np.zeros([self.nb_steps,boot_size])
AttributeError: BivariateKDE instance has no attribute 'nb_steps'

Can you tell me why the BivariateKDE instance has no attribute 'nb_steps'?
Can you please offer me the code for obtaining the bootstrap confidence interval for a BivariateKDE contour?
Many thanks and looking forward to your kind reply.

Sincerely,

John Wang

**Comment by aubreyeckert** [comment]
@wyg110sjtu Thank you for your interest in the WDRT! Please refer to the documentation of the bootstrap function to answer this question. The example in the documentation provides the steps to generating a bootstrap sample for any contour method:

            import WDRT.ESSC as ESSC
            
            # Pull spectral data from NDBC website
            buoy46022 = ESSC.Buoy('46022','NDBC')
            buoy46022.fetchFromWeb()
            
            # Create PCA EA object for buoy
            pca46022 = ESSC.PCA(buoy46022)
            
            # Declare required parameters
            Time_SS = 1.  # Sea state duration (hrs)
            Time_r = 100  # Return periods (yrs) of interest
            nb_steps = 1000  # Enter discretization of the circle in the normal space (optional)
            
            # Contour generation
            Hs_Return, T_Return = pca46022.getContours(Time_SS, Time_r,nb_steps)
            
            # Calculate boostrap confidence interval
            contourmean_Hs, contourmean_T = pca46022.bootStrap(boot_size=10)

In order to generate the bootstrap, you first need to generate an initial contour with the nb_steps parameter. I believe this is where your error is coming from.

**Comment by wyg110sjtu** [comment]
Dear aubrey:

Thanks for the response.

I ran the following codes according to your advice. 

=================================================================
import WDRT.ESSC as ESSC     

# Pull spectral data from NDBC website
buoy46022 = ESSC.Buoy('46022','NDBC')
buoy46022.fetchFromWeb()
        
# Create EA objects for remaining contour methods
BivariateKDE46022 = ESSC.BivariateKDE(buoy46022, bw = [0.0417, 0.1340], logTransform = False)

# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_r = 100  # Return periods (yrs) of interest
nb_steps = 1000  # Enter discretization of the circle in the normal space (optional)
        
# Contour generation
KDE_Hs_Return, KDE_T_Return = BivariateKDE46022.getContours(Time_SS, Time_r,nb_steps)

# Calculate boostrap confidence interval
contourmean_Hs, contourmean_T = BivariateKDE46022.bootStrap(boot_size=10)
=================================================================

However, I obtained the following warnings on my computer screen:

 

Traceback (most recent call last):

  File "C:/WDRT2019H/WDRT-master/examples/b2.py", line 22, in <module>

    KDE_Hs_Return, KDE_T_Return = BivariateKDE46022.getContours(Time_SS, Time_r,nb_steps)

TypeError: getContours() takes exactly 3 arguments (4 given)

 

 

Sincerely,

 

John Wang

**Comment by ssolson** [comment]
John,

~~I was not able to reproduce the error you describe above. I was able to copy, paste, and run the code provided by @aubreyeckert  without errors. Without being able to replicate the error I cannot provide anything beyond general advice. I would suggest the following:~~

~~Please make sure you have not modified the code source, please make sure you have correctly installed WDRT as specified on the install page, please make sure the other examples run without errors.~~

I misunderstood. Apologies. We are considering your code.

**Comment by aubreyeckert** [comment]
@wyg110sjtu I believe you may have encountered a code bug. The bootstrap function requires nb_steps but the KDE contour does not. As a workaround, you should be able to declare this variable for the EA object as follows:

BivariateKDE46022 = ESSC.BivariateKDE(buoy46022, bw = [0.0417, 0.1340], logTransform = False)
# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_r = 100  # Return periods (yrs) of interest
nb_steps = 1000  # Enter discretization of the circle in the normal space (optional)
# Contour generation
BivariateKDE46022.nb_steps=nb_steps
KDE_Hs_Return, KDE_T_Return = BivariateKDE46022.getContours(Time_SS, Time_r)
contourmean_Hs, contourmean_T = BivariateKDE46022.bootStrap(boot_size=10)

**Comment by ssolson** [comment]
Hey John,

There are a couple more issues with this solution I hope to create a pull request to fix these issues by tomorrow. 

Specifically in  ESSC.py  before line 442 we need to create an elif statement to consider the KDE method to create the `essccopy`. Then in the calculation of the KDE method, we need to save the time_ss and time_r to the object for use on line 442 of ESSC.py

There could be additional fixes needed but these have been identified at this point.

**Comment by wyg110sjtu** [comment]
Dear Aubrey:

     Thanks for the response. I ran the following codes according to your advice:
=================================================================
import numpy as np
import WDRT.ESSC as ESSC
import copy
import matplotlib.pyplot as plt

# Create buoy object, in this case for Station #44020
buoy44020 = ESSC.Buoy('44020', 'NDBC')
# Read data from ndbc.noaa.gov
buoy44020.fetchFromWeb()
buoy44020.saveAsH5('NDBC44020.h5')

# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_R = 50  # Return periods (yrs) of interest
nb_steps = 1000

# Create EA objects for remaining contour methods
BivariateKDE44020 = ESSC.BivariateKDE(buoy44020, bw = [0.0491,0.1798], logTransform = False)

# Calculate contours for all remaining contour methods
KDE_Hs_Return, KDE_T_Return = BivariateKDE44020.getContours(Time_SS, Time_R)
BivariateKDE44020.nb_steps=nb_steps
KDE_Hs_Return, KDE_T_Return = BivariateKDE44020.getContours(Time_SS, Time_R)
contourmean_Hs, contourmean_T = BivariateKDE44020.bootStrap(boot_size=10)
 =================================================================

However, I obtained the following warnings on my computer screen:
Traceback (most recent call last):

  File "G:/WDRT2019/WDRT-master/examples/example_envSampling_bPCAc44020TpBootR.py", line 36, in <module>
    contourmean_Hs, contourmean_T = BivariateKDE44020.bootStrap(boot_size=10)
  File "build\bdist.win-amd64\egg\WDRT\ESSC.py", line 381, in bootStrap
    Hs_Return_Boot[:,i],T_Return_Boot[:,i] = essccopy.getContours(self.time_ss, self.time_r, self.nb_steps)
AttributeError: 'NoneType' object has no attribute 'getContours'

Can you please help me to solve this problem?

Sincerely,
John

**Comment by wyg110sjtu** [comment]
Dear ssolson:

      Many thanks for your kind response. Your helpful work is greatly appreciated!

Sincerely,

John

**Comment by ssolson** [comment]
Hey John,

So in short at this time, the official WDRT will not support bootstrap on the Bivariate KDE method but for your research, I have attached a modified version of ESSC.py which will perform the analysis. I make no guarantees towards its correctness. The solution I get out of using the attached version of ESSC.py is: 
![image](https://user-images.githubusercontent.com/13438942/88717164-59bb0500-d0dd-11ea-8e6c-2166a51347d8.png)

[ESSC.zip](https://github.com/WEC-Sim/WDRT/files/4990940/ESSC.zip)

The reason we are not going to push this into production is the possibility of the KDE returning multiple contour levels as shown in the plot below generated by @aubreyeckert below:

![image](https://user-images.githubusercontent.com/13438942/88717795-507e6800-d0de-11ea-8811-e65f77ce97a9.png)

The implications of the small red contour "island" in addtion to the "primary" contour on the overall bootstrap results would require some research and verification which this project does not currently have the development budget for. 

If you have found the WDRT useful and pursue further research into this method please consider working with us to incorporate your research in WDRT. Again thank you for your interest in this project.

**Comment by wyg110sjtu** [comment]
Dear ssolson:

  Thanks for your help and your new code ESSC.zip <https://github.com/WEC-Sim/WDRT/files/4990940/ESSC.zip> . I have installed it and subsequently run the  following codes:

=================================================================
import numpy as np
import WDRT.ESSC as ESSC
import copy
import matplotlib.pyplot as plt

# Create buoy object, in this case for Station #44020
buoy44020 = ESSC.Buoy('44020', 'NDBC')

# Read data from ndbc.noaa.gov
buoy44020.fetchFromWeb()
buoy44020.saveAsH5('NDBC44020.h5')

# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_R = 50  # Return periods (yrs) of interest
nb_steps = 1000

# Create EA objects for remaining contour methods
BivariateKDE44020 = ESSC.BivariateKDE(buoy44020, bw = [0.0491,0.1798], logTransform = False)
# Calculate contours for all remaining contour methods
KDE_Hs_Return, KDE_T_Return = BivariateKDE44020.getContours(Time_SS, Time_R)
BivariateKDE44020.nb_steps=nb_steps
KDE_Hs_Return, KDE_T_Return = BivariateKDE44020.getContours(Time_SS, Time_R)
contourmean_Hs, contourmean_T = BivariateKDE44020.bootStrap(boot_size=10)
 =================================================================

However, I still obtained the following warnings on my computer screen: 

Traceback (most recent call last):
  File "C:/Users/bsp/Desktop/112.py", line 65, in <module>
    contourmean_Hs, contourmean_T = BivariateKDE44020.bootStrap(boot_size=10)
  File "C:\Users\bsp\Anaconda6\lib\site-packages\WDRT\ESSC.py", line 381, in bootStrap
    Hs_Return_Boot[:,i],T_Return_Boot[:,i] = essccopy.getContours(self.time_ss, self.time_r, self.nb_steps)

AttributeError: 'NoneType' object has no attribute 'getContours'

 
Can you please help me find what’s wrong with my codes?

Thanks

John

**Comment by ssolson** [comment]
Hey John,

Aubrey has pointed out to me that the image I sent you the contour is showing no variation from the mean therefore you will need to check the sampling of the bootstrap KDE method I sent you as the solution is incorrect.

ESSC.py on line 381 is not the one shown in your traceback of the WDRT master or the version I sent you. I would suggest you navigate to "C:\Users\bsp\Anaconda6\lib\site-packages\WDRT\ESSC.py" and make sure you have the version of ESSC.py you want there.

Again if you do pursue this research of checking the KDE sampling please consider sharing your work with us here to help the project out.
