### ISSUE TITLE
double-Weibull distribution fitting

### ISSUE THREAD

**Issue by wyg110sjtu** [WEC-Sim/WDRT#49]
Deaer Aubrey:
   In your paper ‘Application of principal component analysis (PCA) and improved joint probability distributions to the inverse first-order reliability method (I-FORM) for predicting extreme sea states“ you stated that for NDBC 46212:
"In an effort to find support for the much higher maximum Hs values obtained using principal component analysis and the modified I-FORM method, the traditional methodology was implemented with an updated double-Weibull distribution fitting that provided a better fit for the distribution tails of the significant wave height data. The results of this exploration are shown in Fig. 12. These show that the improvement of distribution fitting in the implementation of the traditional methodologies that focuses on fitting distribution tails can result in much highe rvalues for the maximum significant wave height, supporting the maximum values found in this work.". 
Are you willing to kindly share the WDRT codes for the "double-Weibull distribution fitting" IFORM method with me?

Sincerely,

John Wang

**Comment by aubreyeckert** [comment]
@wyg110sjtu Thank you for your interest in this work. The double-Weibull calculations are not included the WDRT or in the Matlab version of the ESSC as these were completed as an exploratory study support of the aforementioned paper and were not intended to be presented as an option for contour calculations. Because of this, the scripts for making this calculation are not available to be shared.

**Comment by wyg110sjtu** [comment]
Dear Aubrey:

 

     Are you willing to kindly send the file 'NDBC46022_1996_2012_Hs_Te.mat' to me at wyg110@sjtu.edu.cn <mailto:wyg110@sjtu.edu.cn> ?

 

Sincerely,

 

John Wang

 

 

 

发件人: aubreyeckert <notifications@github.com> 
发送时间: 2020年8月18日 0:22
收件人: WEC-Sim/WDRT <WDRT@noreply.github.com>
抄送: wyg110sjtu <wyg110@sjtu.edu.cn>; Mention <mention@noreply.github.com>
主题: Re: [WEC-Sim/WDRT] double-Weibull distribution fitting (#49)

 

@wyg110sjtu <https://github.com/wyg110sjtu>  Thank you for your interest in this work. The double-Weibull calculations are not included the WDRT or in the Matlab version of the ESSC as these were completed as an exploratory study support of the aforementioned paper and were not intended to be presented as an option for contour calculations. Because of this, the scripts for making this calculation are not available to be shared.

**Comment by wyg110sjtu** [comment]
Dear Aubrey:

 

     Are you willing to kindly send the file 'NDBC46022_1996_2012_Hs_Te.mat' to me at wyg110@sjtu.edu.cn <mailto:wyg110@sjtu.edu.cn> ?

 

Sincerely,

 

John Wang

 

发件人: aubreyeckert <notifications@github.com> 
发送时间: 2020年8月18日 0:22
收件人: WEC-Sim/WDRT <WDRT@noreply.github.com>
抄送: wyg110sjtu <wyg110@sjtu.edu.cn>; Mention <mention@noreply.github.com>
主题: Re: [WEC-Sim/WDRT] double-Weibull distribution fitting (#49)

 

@wyg110sjtu <https://github.com/wyg110sjtu>  Thank you for your interest in this work. The double-Weibull calculations are not included the WDRT or in the Matlab version of the ESSC as these were completed as an exploratory study support of the aforementioned paper and were not intended to be presented as an option for contour calculations. Because of this, the scripts for making this calculation are not available to be shared.
