### ISSUE TITLE
Environmental contours on custom Hs/Tp data

### ISSUE THREAD

**Issue by mmartini1987** [WEC-Sim/WDRT#52]
Hi all,
I am new to the use of WDRT and hopefully my question will not be out of line - apologies in advance if it will.

I would like to apply ESSC (environmental contour) to my personal Hs/Tp 10-years time-series. Looking at the documentation, it looks that I can only use NDBC or CDIP data... is this correct?

Thanks in advance for your support.

Kind regards
Michele

**Comment by ssolson** [comment]
Michele,

Thank you for reaching out and for your interest in the WDRT toolbox. 

The methods within WDRT are numerical so as long as you format your Hs, Tp data to be the same as the format being passed around WDRT for the CDiP/ NDBC data the toolbox will work just the same. I would suggest getting comfortable running one of the examples then modifying the NDBC/CDiP data for your data.

I would also like to point out the WDRT is no longer being supported and is in the process of being transferred into MHKiT https://github.com/MHKiT-Software/MHKiT-Python. The version in MHKiT currently has less functionality. An example of the current functionality can be found in this Jupyter Notebook.
https://github.com/MHKiT-Software/MHKiT-Python/blob/master/examples/environmental_contours.ipynb

If you have any interest in helping add methods from the WDRT to MHKiT or any of your other research please let me know!

Wishing you the best.

**Comment by mmartini1987** [comment]
Hi @ssolson,
Many thanks for replying. I succeeded in using my Hs/Tp data with the WDRT Toolbox - sorry I was just too hasty. 

Thanks also for updating me on MHKiT - I will keep an eye on it and will continue using WDRT which looks a nice tool.

Kind regards,
Michele
