### ISSUE TITLE
Number of cycles in fatigue analysis

### ISSUE THREAD

**Issue by herveg** [WEC-Sim/WDRT#6]
Hi,

I'm trying to understand how to use the WDRT.fatigue module.
More specifically, I am wondering:
1. How the formula giving the damage equivalent load SN is derived as a function of Si, ni, m and N (in http://wec-sim.github.io/WDRT/examples.html#fatigue-analysis). I understand the equivalent damage Palmgren-Miner rule, but cannot understand where this formula comes from. In particular, I do not understand why the damage equivalent load is a _decreasing_ function of the number of cycles expected in the WEC’s design life.
2. Further, considering the example given at "http://wec-sim.github.io/WDRT/examples.html#fatigue-analysis": N1h is directly proportional to the probability of occurrence of a given seastate. Then, looking at the source code of "EqLoad(F, N, m)", it seems to return a value of damage-equivalent load which is decreasing with N: Feq = (sum(R[0:i + 1]**m) / N)**(1 / m). Meaning: the more likely a seastate is to occur, the lesser the equivalent load associated to it. Which goes strongly against my intuition...

Any help is highly appreciated!
Hervé

**Comment by j-vanrij** [comment]
Refer to the S-N curve provided in the documentation. The S-N curve approximates the number of load cycles N to _failure_ at constant load amplitude S. From this figure, I think it makes intuitive sense that more cycles will result in a component failing at lower amplitude loads (i.e. the load is a decreasing function of the number of cycles). All the Palmgrem-Miner rule does is find the equivalent constant amplitude load for variable component loading. 
For WEC and wind-turbine analysis, N is usually ‘set,’ and is representative of the design life (such as, 1E+07 for a turbine lifetime of 20 years). Feq is then the equivalent constant amplitude load that the WEC can withstand for N cycles (meaning that a lower Feq is 'worse' and a higher Feq is 'better').

**Comment by herveg** [comment]
Thanks for your answer!
I now understand the meaning of SN slightly better. To fully understand it, could you give an example of how it can be used? Assuming for instance that I obtain an Feq in the same way as in the example, what is the next step?
Also, would you be able to refer to a document where the formula giving the damage equivalent load SN is derived as a function of Si, ni, m and N?
Thanks again!
Hervé

**Comment by herveg** [comment]
Hi again, I think I just understood how the Feq formula is derived.
Using the Pamlgren-Miner linear damage accumulation hypothesis, and the assumption that the combination of Feq and N causes the same amount of damage as the actual load history, I managed to get to the definition of Feq.
However, this yields a definition of Feq which differs from what you wrote above ("Feq is then the equivalent constant amplitude load that the WEC can withstand for N cycles"). As I understand, it would be the load which applied N times would cause the same amount of damage as the actual load history. This also implies that the lower Feq the better.
So I guess I misunderstood something - any help welcome :-)

**Comment by j-vanrij** [comment]
So, I think your understanding is mostly correct – “the load which applied N times would cause the same amount of damage as the actual load history.” But remember, the S-N curve gives the cycles to _failure_, so this is what I was trying to say with “Feq is then the equivalent constant amplitude load that the WEC can with stand for N cycles.” 
The S-N curve (and thus the Palmgrin-Minor rule) can be used to either predict the fatigue strength for a set N, as was done in the example provided, or in reverse, to predict the fatigue life for the expected loading, for which, we do not have an example yet.
However, I am NOT a fatigue expert - to obtain a detailed understanding of fatigue analysis you would be much better off referring to a textbook, design standard or even a website specifically dedicated to fatigue analysis. 
We do appreciate your questions though! And, in the next year or so we will try to refine the WDRT functions and provide more examples of their usage in WEC design. Thanks!
